workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "00 16,22 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
   build-branch:
     jobs:
       - hold-job:
           type: approval
           filters:
               branches:
                 ignore:
                   - master
       - build:
           requires:
             - hold-job
version: 2
jobs:
 build:
   machine: true
   steps:
    # downloads
     - checkout

     # build the application image
     - run: docker build -t codebar_scraper:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker run --rm -e WEBHOOK_URL=${WEBHOOK_URL} -e SCRIPT_URL=${SCRIPT_URL} codebar_scraper:$CIRCLE_BRANCH
