#workflows:
#   version: 2
#   nightly:
#     triggers:
#       - schedule:
#           cron: "50 10,20 * * *"
#           filters:
#             branches:
#               only:
#                 - master
#     jobs:
#       - build
version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t codebar_scraper:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker run --rm -e WEBHOOK_URL=${WEBHOOK_URL} -e SCRIPT_URL=${SCRIPT_URL} codebar_scraper:$CIRCLE_BRANCH